version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/scam-web-manger
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 180
      runas: root
    - BeforeInstall:
      location: scripts/before_install.sh
      timeout: 180
      runas: root
    - ApplicationStart:
      location: scripts/application_start.sh
      timeout: 300
      runas: root
